Repository JibChain-LLC/jibchain-poc, pull requests merged in 2024-12, with the labels that each got.

#18 Jib 40
  public/arrow-right.svg
  public/dollar.jpg
  public/zoom.jpg
  src/app/(dashboard)/suppliers/_components/supplier-modal.tsx
  src/app/(dashboard)/suppliers/_components/suppliers-header.tsx
  src/app/(dashboard)/suppliers/_components/suppliers-table.tsx
  src/app/(dashboard)/suppliers/page.tsx
  src/app/globals.css
  src/components/global-impact/global-impact-table.tsx
  src/components/overview/overview-card-component.tsx
  src/components/overview/overview-summary-component.tsx
  src/components/tabs/tabs.tsx
  src/components/ui/data-table.tsx
  src/images/summary.svg
  src/utils/utils.ts
Labels: UI/UX

#21 Jib 25
  src/app/(dashboard)/dashboard/_components/risk-container.tsx
  src/app/(dashboard)/suppliers/_components/suppliers-header.tsx
  src/components/defaul-components/time-frame.tsx
  src/components/organization/organization-risk.tsx
  src/components/ui/select.tsx
  src/utils/utils.ts
Labels: UI/UX

#41 Organizations: extend org schema to handle addresses
  src/app/(dashboard)/organization/_components/change-role-select.tsx
  src/app/(dashboard)/organization/_components/invite-dialog.tsx
  src/app/(dashboard)/organization/_components/user-table.tsx
  src/app/(dashboard)/organization/create/_components/create-org-form/create-org-form.tsx
  src/app/(dashboard)/organization/create/page.tsx
  src/app/(dashboard)/organization/page.tsx
  src/components/ui/form.tsx
  src/db/schema.ts
  src/enums.ts
  src/lib/server/shared/auth-check.ts
  src/trpc/routes/org/org-create.ts
  src/trpc/routes/org/org-delete.ts
  src/trpc/routes/org/org-invite-create.ts
  src/trpc/routes/org/org-invite-delete.ts
  src/trpc/routes/org/org-invite-update.ts
  src/trpc/routes/org/org-member-delete.ts
  src/trpc/routes/org/org-member-update.ts
  src/trpc/schemas.ts
  supabase/migrations/0006_thankful_stepford_cuckoos.sql
  supabase/migrations/0007_fine_mojo.sql
  supabase/migrations/0008_fluffy_raider.sql
  supabase/migrations/meta/0006_snapshot.json
  supabase/migrations/meta/0007_snapshot.json
  supabase/migrations/meta/0008_snapshot.json
  supabase/migrations/meta/_journal.json
Labels: enhancement, backend

#42 Risk Alerts: risk alerts schema creation
  drizzle.config.ts
  src/app/(dashboard)/organization/join/page.tsx
  src/app/(dashboard)/organization/no-member/page.tsx
  src/app/(dashboard)/organization/page.tsx
  src/components/organization-card.tsx
  src/db/ai-schema.ts
  src/db/index.ts
  src/db/schema/auth.ts
  src/db/schema/public.ts
  src/db/schema/risks.ts
  src/enums.ts
  src/lib/server/shared/auth-check.ts
  src/lib/types.ts
  src/trpc/routes/org/org-create.ts
  src/trpc/routes/org/org-delete.ts
  src/trpc/routes/org/org-invite-accept.ts
  src/trpc/routes/org/org-invite-create.ts
  src/trpc/routes/org/org-invite-delete.ts
  src/trpc/routes/org/org-invite-list.ts
  src/trpc/routes/org/org-invite-update.ts
  src/trpc/routes/org/org-member-delete.ts
  src/trpc/routes/org/org-member-list.ts
  src/trpc/routes/org/org-member-update.ts
  src/trpc/schemas.ts
  supabase/migrations/0009_funny_boom_boom.sql
  supabase/migrations/0010_loose_tarantula.sql
  supabase/migrations/0011_blue_texas_twister.sql
  supabase/migrations/meta/0009_snapshot.json
  supabase/migrations/meta/0010_snapshot.json
  supabase/migrations/meta/0011_snapshot.json
  supabase/migrations/meta/_journal.json
Labels: backend

#44 Auth flow: move routes, update designs
  src/app/(auth)/getting-started/page.tsx
  src/app/(auth)/join/_components/no-user.tsx
  src/app/(auth)/join/_components/not-user.tsx
  src/app/(auth)/join/_components/same-user.tsx
  src/app/(auth)/join/page.tsx
  src/app/(auth)/layout.tsx
  src/app/(auth)/login/_components/login-form.tsx
  src/app/(auth)/logout/page.tsx
  src/app/(auth)/organization/create/_components/create-org-form/create-org-form.tsx
  src/app/(auth)/organization/create/_components/create-org-form/index.ts
  src/app/(auth)/organization/create/page.tsx
  src/app/(auth)/signup/_components/sign-up-form/sign-up-form.tsx
  src/app/(dashboard)/organization/_components/invite-actions.tsx
  src/app/(dashboard)/organization/create/page.tsx
  src/app/(dashboard)/organization/join/_components/no-user.tsx
  src/app/(dashboard)/organization/join/_components/not-user.tsx
  src/app/(dashboard)/organization/no-member/page.tsx
  src/middleware.ts
  src/routes.ts
Labels: UI/UX

#43 Initial pipeline
  next.config.mjs
  package-lock.json
  package.json
  src/app/api/pipeline/_helpers/categorizer.ts
  src/app/api/pipeline/_helpers/gen-all.ts
  src/app/api/pipeline/_helpers/performance-marker.ts
  src/app/api/pipeline/_helpers/shared.ts
  src/app/api/pipeline/_helpers/summarizer.ts
  src/app/api/pipeline/_route.ts
  src/app/api/pipeline/route.ts
  src/db/schema/risks.ts
  src/enums.ts
  src/mappings.ts
  supabase/migrations/0012_cooing_scalphunter.sql
  supabase/migrations/0013_sour_juggernaut.sql
  supabase/migrations/0014_organic_warbird.sql
  supabase/migrations/0015_hesitant_mattie_franklin.sql
  supabase/migrations/0016_stormy_tiger_shark.sql
  supabase/migrations/meta/0012_snapshot.json
  supabase/migrations/meta/0013_snapshot.json
  supabase/migrations/meta/0014_snapshot.json
  supabase/migrations/meta/0015_snapshot.json
  supabase/migrations/meta/0016_snapshot.json
  supabase/migrations/meta/_journal.json
Labels: backend, WIP 👷‍♂️
